[build]
command = """
apt-get update && \
apt-get install -y gcc python3-dev libffi-dev libssl-dev && \
pip install --upgrade pip setuptools wheel && \
pip install -r requirements.txt --no-cache-dir
"""
